stages:
  - install
  - test
  - publish

default:
  image: node:22
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
  tags:
    - docker
    - linux
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - .pnpm-store
      - node_modules

install:
  stage: install
  script:
    - pnpm install

test:
  stage: test
  script:
    - pnpm lint
    - pnpm test
  allow_failure: true

publish:
  stage: publish
  script:
    # build library
    - pnpm build:lib
    # publish
    - echo //artifact.production.aptima.com/repository/:_authToken=$NPM_AUTH_TOKEN > .npmrc
    - echo $(cat .npmrc)
    - pnpm publish --no-git-checks
    # build docs site
    - echo "VITE_BASE_URL=/core/library/aptima-ui/aptima-ui/" >> .env
    - pnpm build:docs
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  pages:
    publish: dist/docs
